name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Publish Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            your-username/your-repository:latest
            your-username/your-repository:${{ github.sha }}
            your-username/your-repository:${{ github.ref_slug }}

      - name: Display Docker Image Tags
        run: |
          echo "Docker Image Tags:"
          echo ${{ steps.docker_build.outputs.tags }}
